server:
  port: 8085
  servlet:
    context-path: /user-svc

spring:
  application:
    name: ems-user-service
  config:
    import: optional:configserver:http://localhost:8082

  datasource:
    url: jdbc:mysql://localhost:3306/userdatabase
    username: devuser
    password: devuser@pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 300000   # 5 * 60 * 1000
  refreshToken:
    expiration-time: 10   # 10 * 60 * 1000